Repository the-vision/jarvis-web, pull requests merged in 2020-04, with the labels that each got.

#16 Addition of responsive navigation bar
  src/App.vue
  src/components/Navigation.vue
  src/views/Home.vue
Labels: gssoc20, medium

#22 Added CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: easy, gssoc20

#23 Addition of footer
  src/App.vue
  src/components/Footer.vue
Labels: gssoc20, medium

#24 project details added
  src/components/About.vue
Labels: gssoc20, medium

#25 Add ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
  .github/pull_request_template.md
Labels: easy, gssoc20

#27 Added Github Actions
  .github/workflows/greetings.yml
  .github/workflows/language.yml
Labels: easy, gssoc20

#30 UI changes
  src/components/Footer.vue
  src/components/LandingPage.vue
  src/components/Navigation.vue
Labels: enhancement

#31 Added search and send icons
  src/assets/search.svg
  src/assets/send.svg
  src/views/Home.vue
Labels: easy, gssoc20

#34 Addition of 404 page
  src/components/ErrorDisplay.vue
  src/router/index.js
  src/views/ErrorPage.vue
Labels: gssoc20, medium

#32 Project page
  src/App.vue
  src/assets/background.jpg
  src/components/Navigation.vue
  src/router/index.js
  src/views/Project.vue
Labels: gssoc20, medium
